
modLoader="javafml"

loaderVersion="${loader_version_range}"

license="${mod_license}"


[[mods]]

modId="avaritia_expand"
logoFile = "logo.png"
version="${mod_version}"
displayName="${mod_name}"

authors="${mod_authors}"


description='''${mod_description}'''

[[dependencies.${mod_id}]]

    modId="forge"

    mandatory=true

    versionRange="${forge_version_range}"

    ordering="NONE"

    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true

    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
#Avaritia
[[dependencies.${mod_id}]]
modId = "avaritia"
mandatory = true
versionRange = "[1.3.9.0,)"
ordering = "AFTER"
side = "BOTH"